import {
  ClearDay,
  ClearNight,
  Cloudly,
  Fog,
  Hail,
  PartyCloudlyDay,
  PartyCloudlyNight,
  Rain,
  RainSnow,
  RainSnowDays,
  RainSnowNight,
  ShowersDay,
  ShowersNight,
  Sleet,
  Snow,
  Thunder,
  ThunderDay,
  ThunderNight,
  ThunderRain,
  Wind,
} from '../../public/assets/WeatherIcons/index';

export const IconsWeather = {
  cloudy: Cloudly,
  fog: Fog,
  'partly-cloudy-day': PartyCloudlyDay,
  'clear-day': ClearDay,
  'clear-night': ClearNight,
  hail: Hail,
  'partly-cloudy-night': PartyCloudlyNight,
  'rain-snow-showers-day': RainSnowDays,
  'rain-snow-showers-night': RainSnowNight,
  'rain-snow': RainSnow,
  rain: Rain,
  'showers-day': ShowersDay,
  sleet: Sleet,
  'snow-showers-day': ShowersDay,
  'snow-showers-night': ShowersNight,
  snow: Snow,
  'thunder-rain': ThunderRain,
  'thunder-showers-day': ThunderDay,
  'thunder-showers-night': ThunderNight,
  thunder: Thunder,
  wind: Wind,
};
